title: Vesa V채nsk채
description: Blog of a thirty-something Ruby developer living in Helsinki working for Kisko Labs.
highlighter: 'rouge'
author: Vesa V채nsk채
permalink: /:year/:title
url: http://vesavanska.com
plugins:
  - jekyll-feed
feed:
  path: atom.xml
